{
  "openapi": "3.0.0",
  "info": {
    "title": "API Cut Scheduling",
    "description": "This API focuses on scheduling haircuts for multiple barbershops.",
    "contact": {
      "email": "leonardoarrais211@gmail.com"
    },
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost:3000/",
      "description": "Server for development testing"
    }
  ],
  "paths": {
    "/auth/user/created": {
      "post": {
        "summary": "Sign up",
        "description": "Endpoint responsible for creating a user.",
        "tags": ["Users"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserCreated"
              },
              "examples": {
                "user": {
                  "value": {
                    "name": "UserTwo",
                    "email": "usertwo@domain.com",
                    "password": "********",
                    "age": 21
                  }
                }
              }
            }
          }
        },
        "responses": {
          "400": {
            "description": "Email already registered in the system"
          },
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/UserCreated"
                }
              }
            }
          }
        }
      }
    },

    "/auth/user/login": {
      "post": {
        "summary": "Sign in",
        "description": "Endpoint to log in with the user",
        "tags": ["Users"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserLogin"
              },
              "examples": {
                "user": {
                  "value": {
                    "email": "usertwo@domain.com",
                    "password": "********"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "400": {
            "content": {
              "application/json": {
                "examples": {
                  "BlockedUser": {
                    "summary": "User account is lock",
                    "value": {
                      "statusCode": 400,
                      "message": "Your account has been blocked for consecutive failed attempts"
                    }
                  },
                  "AccountLock": {
                    "summary": "Account deactiveted",
                    "value": {
                      "statusCode": 400,
                      "message": "Your account has been blocked. Please try again later"
                    }
                  },
                  "FailedAttemptsSignUp": {
                    "summary": "Invalid credentials",
                    "value": {
                      "statusCode": 400,
                      "message": "E-mail or password incorrect!"
                    }
                  }
                }
              }
            }
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/UserLogin"
                }
              }
            }
          }
        }
      }
    },

    "/auth/user/forgot-password": {
      "post": {
        "summary": "Forgot your password",
        "description": "Endpoint to send an email to reset the user's password",
        "tags": ["Users"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserForgotPassword"
              },
              "examples": {
                "user": {
                  "value": {
                    "email": "usertwo@domain.com"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "400": {
            "content": {
              "application/json": {
                "examples": {
                  "FailedSendMail": {
                    "summary": "Failed to send e-mail",
                    "value": {
                      "statusCode": 400,
                      "message": "Failed to send e-mail to user request"
                    }
                  },
                  "UnknownError": {
                    "summary": "Unknown error detected",
                    "value": {
                      "statusCode": 400,
                      "message": "Unknown error detected in application"
                    }
                  },
                  "CredentialsIncorrect": {
                    "summary": "Invalid credentials",
                    "value": {
                      "statusCode": 400,
                      "message": "If the email is correct, we will send you a link to change your password"
                    }
                  }
                }
              }
            }
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "examples": {
                  "user": {
                    "value": {
                      "message": "If the email is correct, we will send you a link to change your password"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },

    "/auth/user/updated": {
      "put": {
        "summary": "Updated user infos",
        "description": "Endpoint for updating user information",
        "tags": ["Users"],
        "security": [{ "bearerAuth": [] }],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserUpdated"
              },
              "examples": {
                "user": {
                  "value": {
                    "name": "user",
                    "age": 21
                  }
                }
              }
            }
          }
        },
        "responses": {
          "400": {
            "content": {
              "application/json": {
                "examples": {
                  "UserNotFound": {
                    "value": {
                      "message": "Error: user not found"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "content": {
              "application/json": {
                "examples": {
                  "TokenInvalidOrExpired": {
                    "value": {
                      "message": "Error: token invalid or expired"
                    }
                  },
                  "PayloadIncomplete": {
                    "value": {
                      "message": "Error: payload incomplete"
                    }
                  }
                }
              }
            }
          },
          "403": {
            "content": {
              "application/json": {
                "examples": {
                  "TokenNotFound": {
                    "value": {
                      "message": "Token is missing"
                    }
                  }
                }
              }
            }
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "examples": {
                  "userUpdated": {
                    "value": {
                      "message": "Your information has been changed successfully"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },

    "/auth/user/reset-password/{token}": {
      "put": {
        "summary": "Reset password user",
        "description": "Endpoint to reset user password",
        "tags": ["Users"],
        "parameters": [
          {
            "name": "token",
            "in": "path",
            "description": "Token in URL path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserResetPassword"
              },
              "examples": {
                "user": {
                  "value": {
                    "newPassword": "***********"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "400": {
            "content": {
              "application/json": {
                "examples": {
                  "TokenExpired": {
                    "value": {
                      "message": "Token invalid or expired"
                    }
                  },
                  "SamePassword": {
                    "value": {
                      "message": "Your new password must not be the same as your current one"
                    }
                  }
                }
              }
            }
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "examples": {
                  "user": {
                    "value": {
                      "message": "Your password has been reset successfully!"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "UserCreated": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "age": {
            "type": "number"
          }
        }
      },
      "UserLogin": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        }
      },
      "UserForgotPassword": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string"
          }
        }
      },
      "UserUpdated": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "age": {
            "type": "number"
          }
        }
      },
      "UserResetPassword": {
        "type": "object",
        "properties": {
          "password": {
            "type": "string"
          }
        }
      }
    },
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}
